### ISSUE TITLE
Bug found in testing 

### ISSUE THREAD

**Issue by aberry22** [Macaela-Morrison/IS147-Group-A-Project#11]
<img width="349" alt="Screenshot 2024-12-02 150509" src="https://github.com/user-attachments/assets/f7aaea39-6fd9-4c92-b2de-78c64152daca">

**Comment by Macaela-Morrison** [comment]
It seems to be resolved! Let me know when you run through the program again.

**Comment by Macaela-Morrison** [comment]
Closing this issue now as we have a different bug thread and this particular issue was resolved
