### ISSUE TITLE
Math calculation methods

### ISSUE THREAD

**Issue by Macaela-Morrison** [Macaela-Morrison/IS147-Group-A-Project#6]

**Comment by AngryDaniel79** [comment]
Methods:

calcTotalExpenses() - Calculate total expenses across all categories

calcRecurringExpenses() - Calculate the total of the recurring expenses

calcNonRecurringExpenses() - Calculate the total of the non-recurring expenses

calcRemainingBalance() - Will keep a running total of the amount of money the user has left. Will be displayed on the main menu
