### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by Macaela-Morrison** [Macaela-Morrison/IS147-Group-A-Project#7]

**Comment by aberry22** [comment]
Basic tests:

User input validation:
Check for correct user input when adding expenses. 
-Must enter non-zero number for expense
-Must add a valid name for expense - no repeating names(maybe)


Logic verification:
-Run various features with simple inputs and verify that the math calculations are working as intended
-No division by zero
-Make sure all numbers are doubles to avoid floating point errors


Find and fix any runtime errors

**Comment by Macaela-Morrison** [comment]
This looks good. We can add and document more tests here as needed

**Comment by Macaela-Morrison** [comment]
I added some test data that you can use. Also the menu code is ready for testing.
