### ISSUE TITLE
Demo setup

### ISSUE THREAD

**Issue by Macaela-Morrison** [Macaela-Morrison/IS147-Group-A-Project#9]

**Comment by aberry22** [comment]
Where did you guys wanna start with the project?

**Comment by Macaela-Morrison** [comment]
I created some base classes we can start with. Lillian is working on the menu. We're also going to need a switch statement to handle menu options.

**Comment by Macaela-Morrison** [comment]
Many features are now complete. We will run through the complete Demo when finishing the presentation at our next meeting. @lbryso @aberry22 @AngryDaniel79 @HDanayak
